[profile.default]
solc = "0.8.19"
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.2/src/",
    "foundry-devops/=dependencies/foundry-devops-0.2.2/src/",
    "solmate/=dependencies/solmate-6.7.0/src/",
    "chainlink/=dependencies/@chainlink-contracts-1.2.0/src/v0.8/",
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[dependencies]
forge-std = { version = "1.9.2" }
foundry-devops = { version = "0.2.2" }
solmate = { version = "6.7.0" }
"@chainlink-contracts" = { version = "1.2.0" }

[soldeer]
remappings_generate = false
remappings_regenerate = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
